# Generated by Django 5.1.2 on 2025-04-30 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='fechaHora',
            new_name='fechahora_creada',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='tipoSistema',
            new_name='tipo_sistema',
        ),
        migrations.RenameField(
            model_name='notificacion',
            old_name='Usuario',
            new_name='usuario_destino',
        ),
    ]
