# Generated by Django 5.1.2 on 2025-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacion', '0002_rename_fechahora_notificacion_fechahora_creada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificacion',
            old_name='tipo_sistema',
            new_name='notificacion_de_sistema',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='fechahora_creada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
