# Generated by Django 5.1.2 on 2025-04-17 01:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificacion', '0001_initial'),
        ('servicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(null=True)),
                ('fechaSolicitud', models.DateField(blank=True, null=True)),
                ('fechaTrabajo', models.DateField(blank=True, null=True)),
                ('fechaValoracion', models.DateField(blank=True, null=True)),
                ('valoracion', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('estado', models.CharField(choices=[('I', 'Iniciado'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='I', max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_cliente', to=settings.AUTH_USER_MODEL)),
                ('notificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_notificacion', to='notificacion.notificacion')),
                ('proveedorServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='servicio.proveedorservicio')),
            ],
        ),
    ]
