# Generated by Django 5.1.2 on 2025-04-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('I', 'Iniciado'), ('PA', 'Pendiente de Aceptación'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='I', max_length=15),
        ),
    ]
