# Generated by Django 5.1.2 on 2025-05-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_alter_solicitud_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='notificacion',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('PA', 'Pendiente de Aceptación'), ('I', 'Iniciado'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='PA', max_length=25),
        ),
    ]
