# Generated by Django 5.1.2 on 2025-05-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_remove_solicitud_notificacion_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
