# Generated by Django 5.1.2 on 2025-05-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0004_alter_solicitud_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fechaSolicitud',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
