# Generated by Django 5.0.4 on 2025-06-07 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='desdeHora',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='hastaHora',
        ),
        migrations.CreateModel(
            name='HorarioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lun'), ('Martes', 'Mar'), ('Miércoles', 'Mie'), ('Jueves', 'Jue'), ('Viernes', 'Vie'), ('Sábado', 'Sab'), ('Domingo', 'Dom')], max_length=10)),
                ('desdeHora', models.TimeField()),
                ('hastaHora', models.TimeField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='servicio.servicio')),
            ],
        ),
    ]
