# Generated by Django 5.1.2 on 2025-05-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_direccion_alter_usuario_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
