# Generated by Django 5.0.4 on 2025-07-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_expo_push_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoPerfil',
            field=models.ImageField(blank=True, default='usuario/media/imagenesUsuario/empty.jpg', null=True, upload_to='usuario/media/imagenesUsuario'),
        ),
    ]
