# Generated by Django 5.1.2 on 2025-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_usuario_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
