# Generated by Django 5.1.2 on 2025-06-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_expo_push_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='expo_push_token',
            new_name='fcm_token',
        ),
    ]
